-- Generated by main c206c89 schema 18.
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.2
-- Dumped by pg_dump version 17.11 (Debian 17.11-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: swarm_keep_blocked_jobs(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.swarm_keep_blocked_jobs() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF OLD.status='active' AND NEW.status<>'active' AND NEW.closed_by='auto'
           AND EXISTS (SELECT 1 FROM blockers b WHERE b.job=OLD.job AND b.state='open'
                       AND (b.protection_rule='always' OR (b.protection_rule='addressed' AND b.waiting_on <> 'external') OR b.until>now())) THEN RETURN NULL; END IF;
        RETURN NEW;
    END $$;


--
-- Name: swarm_keep_goal_jobs(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.swarm_keep_goal_jobs() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.status <> 'active' AND OLD.status = 'active' AND NEW.goal IS NOT NULL AND length(NEW.goal) > 0
       AND NEW.verdict IS DISTINCT FROM 'met' AND NEW.closed_by = 'auto'
       AND NEW.outcome LIKE 'auto-closed: no live agents%' THEN
        RETURN NULL;
    END IF;
    RETURN NEW;
END $$;


--
-- Name: swarm_notify(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.swarm_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN PERFORM pg_notify('swarm_board', NEW.id::text); RETURN NEW; END $$;


--
-- Name: swarm_state_notify(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.swarm_state_notify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN PERFORM pg_notify('swarm_state', TG_TABLE_NAME); RETURN NULL; END $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agent_routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_routes (
    agent_key text NOT NULL,
    session_id text,
    state text NOT NULL,
    job text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agent_routes_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'unverified'::text, 'final'::text])))
);


--
-- Name: agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agents (
    agent_key text NOT NULL,
    name text NOT NULL,
    job text NOT NULL,
    role text,
    host text,
    joined_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen timestamp with time zone DEFAULT now() NOT NULL,
    last_read_id bigint DEFAULT 0 NOT NULL,
    left_at timestamp with time zone,
    state text DEFAULT 'started'::text NOT NULL,
    tool_calls integer DEFAULT 0 NOT NULL,
    current_tool text,
    tool_started_at timestamp with time zone,
    last_post_at timestamp with time zone,
    roster_seen text,
    roster_synced_at timestamp with time zone,
    memory_recalled_at timestamp with time zone,
    memory_seen text[] DEFAULT '{}'::text[] NOT NULL,
    remembered_at timestamp with time zone,
    nudged_at timestamp with time zone,
    reply_reminded_id bigint DEFAULT 0 NOT NULL,
    calls_at_post integer DEFAULT 0 NOT NULL,
    silence_nudged_at timestamp with time zone,
    judge boolean DEFAULT false NOT NULL,
    spawns integer DEFAULT 0 NOT NULL,
    verifier boolean DEFAULT false NOT NULL,
    harness text,
    model text,
    turn_ended_at timestamp with time zone,
    os_user text,
    left_reason text,
    resume_of text,
    CONSTRAINT agents_name_check CHECK ((length(name) > 0)),
    CONSTRAINT agents_state_check CHECK ((state = ANY (ARRAY['started'::text, 'running'::text, 'completed'::text, 'left'::text, 'dead'::text])))
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    job text NOT NULL,
    agent_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    message text NOT NULL,
    to_agent text,
    agent_key text,
    host text,
    CONSTRAINT messages_agent_name_check CHECK ((length(agent_name) > 0))
);


--
-- Name: agent_status; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.agent_status AS
 SELECT a.job,
    a.name,
        CASE
            WHEN a.judge THEN 'judge'::text
            WHEN a.verifier THEN 'verifier'::text
            ELSE a.role
        END AS role,
        CASE
            WHEN (a.state = ANY (ARRAY['completed'::text, 'left'::text, 'dead'::text])) THEN a.state
            WHEN ((a.current_tool IS NOT NULL) AND (a.tool_started_at > (now() - make_interval(mins => 60)))) THEN 'running'::text
            WHEN (a.last_seen < (now() - make_interval(mins => 30))) THEN 'dead'::text
            WHEN (a.last_seen < (now() - make_interval(mins => 5))) THEN 'idle'::text
            ELSE a.state
        END AS status,
    a.current_tool,
    a.tool_calls,
    COALESCE(mc.messages, (0)::bigint) AS messages,
    a.joined_at,
    a.last_seen AS last_contact_at,
    a.last_post_at,
    a.left_at AS ended_at,
    a.host,
    a.agent_key,
    a.harness,
    a.model,
    a.os_user,
    a.left_reason,
    a.resume_of
   FROM (public.agents a
     LEFT JOIN LATERAL ( SELECT count(*) AS messages
           FROM public.messages m
          WHERE ((m.job = a.job) AND (m.agent_name = a.name) AND (m.created_at >= a.joined_at))) mc ON (true));


--
-- Name: blocker_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blocker_events (
    id bigint NOT NULL,
    blocker bigint NOT NULL,
    at timestamp with time zone NOT NULL,
    actor text,
    event text NOT NULL,
    detail text,
    CONSTRAINT blocker_events_event_check CHECK ((event = ANY (ARRAY['opened'::text, 'commented'::text, 'resolved'::text, 'expired'::text, 'overdue'::text, 'reopened'::text])))
);


--
-- Name: blocker_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.blocker_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: blocker_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.blocker_events_id_seq OWNED BY public.blocker_events.id;


--
-- Name: blockers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.blockers (
    id bigint NOT NULL,
    job text NOT NULL,
    kind text NOT NULL,
    waiting_on text NOT NULL,
    reason text NOT NULL,
    until timestamp with time zone,
    default_value text,
    state text NOT NULL,
    created_by text,
    created_at timestamp with time zone NOT NULL,
    resolved_by text,
    resolved_how text,
    resolved_at timestamp with time zone,
    protection_rule text DEFAULT 'addressed'::text NOT NULL,
    CONSTRAINT blockers_protection_rule_check CHECK ((protection_rule = ANY (ARRAY['addressed'::text, 'always'::text, 'deadline'::text]))),
    CONSTRAINT blockers_state_check CHECK ((state = ANY (ARRAY['open'::text, 'resolved'::text, 'expired'::text])))
);


--
-- Name: blockers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.blockers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: blockers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.blockers_id_seq OWNED BY public.blockers.id;


--
-- Name: board_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.board_meta (
    key text NOT NULL,
    value text NOT NULL
);


--
-- Name: job_pauses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_pauses (
    id bigint NOT NULL,
    job text NOT NULL,
    paused_at timestamp with time zone DEFAULT now() NOT NULL,
    paused_by text,
    reason text,
    manifest text NOT NULL,
    resumed_at timestamp with time zone,
    resumed_by text,
    resumed_host text,
    outcome text
);


--
-- Name: job_pauses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.job_pauses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: job_pauses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.job_pauses_id_seq OWNED BY public.job_pauses.id;


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    job text NOT NULL,
    description text,
    created_by text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    task text,
    status text DEFAULT 'active'::text NOT NULL,
    outcome text,
    session_id text,
    activated_at timestamp with time zone,
    finished_at timestamp with time zone,
    project text,
    goal text,
    verdict text,
    verdict_reason text,
    verdict_next text,
    verdict_by text,
    verdict_at timestamp with time zone,
    completion_forced boolean DEFAULT false NOT NULL,
    spawns integer DEFAULT 0 NOT NULL,
    waiting_on text,
    waiting_since timestamp with time zone,
    waiting_until timestamp with time zone,
    max_hours double precision,
    closed_by text,
    supervise boolean DEFAULT true NOT NULL,
    plugin_data text,
    CONSTRAINT jobs_status_check CHECK ((status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'cancelled'::text, 'failed'::text]))),
    CONSTRAINT jobs_verdict_check CHECK ((verdict = ANY (ARRAY['met'::text, 'not_met'::text])))
);


--
-- Name: job_status; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.job_status AS
 SELECT j.job,
    j.status,
    j.description,
    j.task,
    j.outcome,
    j.created_by,
    j.session_id,
    j.created_at,
    j.activated_at,
    j.finished_at,
    COALESCE(s.agents, (0)::bigint) AS agents,
    COALESCE(s.started, (0)::bigint) AS started,
    COALESCE(s.running, (0)::bigint) AS running,
    COALESCE(s.idle, (0)::bigint) AS idle,
    COALESCE(s.completed, (0)::bigint) AS completed,
    COALESCE(s.dead_or_left, (0)::bigint) AS dead_or_left,
    COALESCE(m.messages, (0)::bigint) AS messages,
    GREATEST(s.last_contact_at, m.last_post_at) AS last_activity_at,
    j.project,
    j.goal,
    j.verdict,
    j.verdict_reason,
    j.verdict_by,
    j.verdict_at,
    j.completion_forced,
    ( SELECT a.name
           FROM public.agents a
          WHERE ((a.job = j.job) AND a.judge AND (a.left_at IS NULL))) AS judge,
    j.waiting_on,
    j.waiting_since,
    j.closed_by,
    j.supervise,
    j.verdict_next,
    j.max_hours,
    j.waiting_until,
    COALESCE(( SELECT json_agg(row_to_json(b.*) ORDER BY b.id) AS json_agg
           FROM public.blockers b
          WHERE ((b.job = j.job) AND (b.state = 'open'::text))), '[]'::json) AS blockers,
    ( SELECT count(*) AS count
           FROM public.blockers b
          WHERE ((b.job = j.job) AND (b.state = 'open'::text))) AS open_blockers,
    ( SELECT count(*) AS count
           FROM public.blockers b
          WHERE ((b.job = j.job) AND (b.state = 'open'::text) AND ((b.protection_rule = 'always'::text) OR ((b.protection_rule = 'addressed'::text) AND (b.waiting_on <> 'external'::text)) OR (b.until > now())))) AS protected_blockers,
        CASE
            WHEN (j.status <> 'active'::text) THEN j.status
            WHEN (EXISTS ( SELECT 1
               FROM public.blockers b
              WHERE ((b.job = j.job) AND (b.state = 'open'::text)))) THEN 'waiting'::text
            WHEN (COALESCE(j.waiting_on, ''::text) <> ''::text) THEN 'waiting'::text
            WHEN ((COALESCE(s.started, (0)::bigint) + COALESCE(s.running, (0)::bigint)) > 0) THEN 'active'::text
            WHEN ((COALESCE(j.goal, ''::text) <> ''::text) AND (j.verdict IS DISTINCT FROM 'met'::text) AND (COALESCE(s.idle, (0)::bigint) = 0)) THEN 'waiting (goal not met)'::text
            WHEN (COALESCE(GREATEST(s.last_contact_at, m.last_post_at), j.activated_at, j.created_at) > (now() - make_interval(mins => 5))) THEN 'active'::text
            ELSE 'idle'::text
        END AS shown_status
   FROM ((public.jobs j
     LEFT JOIN ( SELECT a.job,
            (sum(a.n))::bigint AS agents,
            (COALESCE(sum(a.n) FILTER (WHERE (a.status = 'started'::text)), (0)::numeric))::bigint AS started,
            (COALESCE(sum(a.n) FILTER (WHERE (a.status = 'running'::text)), (0)::numeric))::bigint AS running,
            (COALESCE(sum(a.n) FILTER (WHERE (a.status = 'idle'::text)), (0)::numeric))::bigint AS idle,
            (COALESCE(sum(a.n) FILTER (WHERE (a.status = 'completed'::text)), (0)::numeric))::bigint AS completed,
            (COALESCE(sum(a.n) FILTER (WHERE (a.status = ANY (ARRAY['dead'::text, 'left'::text]))), (0)::numeric))::bigint AS dead_or_left,
            max(a.last_contact_at) AS last_contact_at
           FROM ( SELECT a_1.job,
                        CASE
                            WHEN (a_1.state = ANY (ARRAY['completed'::text, 'left'::text, 'dead'::text])) THEN a_1.state
                            WHEN ((a_1.current_tool IS NOT NULL) AND (a_1.tool_started_at > (now() - make_interval(mins => 60)))) THEN 'running'::text
                            WHEN (a_1.last_seen < (now() - make_interval(mins => 30))) THEN 'dead'::text
                            WHEN (a_1.last_seen < (now() - make_interval(mins => 5))) THEN 'idle'::text
                            ELSE a_1.state
                        END AS status,
                    count(*) AS n,
                    max(a_1.last_seen) AS last_contact_at
                   FROM public.agents a_1
                  GROUP BY a_1.job,
                        CASE
                            WHEN (a_1.state = ANY (ARRAY['completed'::text, 'left'::text, 'dead'::text])) THEN a_1.state
                            WHEN ((a_1.current_tool IS NOT NULL) AND (a_1.tool_started_at > (now() - make_interval(mins => 60)))) THEN 'running'::text
                            WHEN (a_1.last_seen < (now() - make_interval(mins => 30))) THEN 'dead'::text
                            WHEN (a_1.last_seen < (now() - make_interval(mins => 5))) THEN 'idle'::text
                            ELSE a_1.state
                        END) a
          GROUP BY a.job) s ON ((s.job = j.job)))
     LEFT JOIN ( SELECT messages.job,
            count(*) AS messages,
            max(messages.created_at) FILTER (WHERE (NOT ((messages.agent_name = 'swarm'::text) AND (messages.message ~~ 'Blocker % expired:%'::text)))) AS last_post_at
           FROM public.messages
          GROUP BY messages.job) m ON ((m.job = j.job)));


--
-- Name: memory_ref_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_ref_images (
    document_id text NOT NULL,
    sha256 text NOT NULL
);


--
-- Name: memory_refs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memory_refs (
    document_id text NOT NULL,
    bank text NOT NULL,
    job text NOT NULL,
    agent_key text NOT NULL,
    agent_name text NOT NULL,
    harness text,
    host text,
    session_id text,
    tool_call_id text,
    writer text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    checked_at timestamp with time zone,
    patched boolean DEFAULT false NOT NULL,
    raw_bytes bigint DEFAULT 0 NOT NULL,
    redactions integer DEFAULT 0 NOT NULL,
    excerpt bytea
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.messages_id_seq OWNED BY public.messages.id;


--
-- Name: name_pool; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.name_pool (
    name text NOT NULL,
    source text NOT NULL,
    CONSTRAINT name_pool_source_check CHECK ((source = ANY (ARRAY['simpsons'::text, 'english'::text])))
);


--
-- Name: restarts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.restarts (
    id bigint NOT NULL,
    job text NOT NULL,
    agent_key text NOT NULL,
    attempt integer NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    reason text NOT NULL,
    old_agent_key text NOT NULL,
    new_agent_key text,
    harness text NOT NULL,
    host text NOT NULL,
    os_user text NOT NULL,
    minutes_cap double precision NOT NULL,
    ended_at timestamp with time zone,
    outcome text
);


--
-- Name: restarts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.restarts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: restarts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.restarts_id_seq OWNED BY public.restarts.id;


--
-- Name: transcript_image_refs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcript_image_refs (
    job text NOT NULL,
    agent_key text NOT NULL,
    sha256 text NOT NULL
);


--
-- Name: transcript_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcript_images (
    sha256 text NOT NULL,
    mime text NOT NULL,
    bytes bigint NOT NULL,
    data bytea NOT NULL,
    first_seen timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: transcripts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcripts (
    job text NOT NULL,
    agent_key text NOT NULL,
    agent_name text NOT NULL,
    role text NOT NULL,
    host text,
    session_id text,
    captured_at timestamp with time zone DEFAULT now() NOT NULL,
    final boolean DEFAULT false NOT NULL,
    raw_bytes bigint NOT NULL,
    stored_bytes bigint NOT NULL,
    redactions integer DEFAULT 0 NOT NULL,
    sha256 text NOT NULL,
    body bytea NOT NULL,
    harness text,
    capture_failed text,
    CONSTRAINT transcripts_role_check CHECK ((role = ANY (ARRAY['subagent'::text, 'orchestrator'::text])))
);


--
-- Name: blocker_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocker_events ALTER COLUMN id SET DEFAULT nextval('public.blocker_events_id_seq'::regclass);


--
-- Name: blockers id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blockers ALTER COLUMN id SET DEFAULT nextval('public.blockers_id_seq'::regclass);


--
-- Name: job_pauses id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_pauses ALTER COLUMN id SET DEFAULT nextval('public.job_pauses_id_seq'::regclass);


--
-- Name: messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages ALTER COLUMN id SET DEFAULT nextval('public.messages_id_seq'::regclass);


--
-- Name: restarts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restarts ALTER COLUMN id SET DEFAULT nextval('public.restarts_id_seq'::regclass);


--
-- Data for Name: agent_routes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agents; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: blocker_events; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.blocker_events VALUES (1, 1, '2026-10-06 09:29:38.320897-07', 'human', 'opened', 'choose a format');
INSERT INTO public.blocker_events VALUES (2, 1, '2026-10-06 09:29:38.514668-07', 'human', 'commented', 'still pending');


--
-- Data for Name: blockers; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.blockers VALUES (1, 'j', 'question', 'human', 'choose a format', NULL, NULL, 'open', 'human', '2026-10-06 09:29:38.320897-07', NULL, NULL, NULL, 'addressed');


--
-- Data for Name: board_meta; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.board_meta VALUES ('schema_version', '18');
INSERT INTO public.board_meta VALUES ('message_max_chars', '200');


--
-- Data for Name: job_pauses; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: jobs; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.jobs VALUES ('j', 'schema 18 job', NULL, '2026-10-06 09:29:38.227831-07', NULL, 'active', NULL, 'S18', '2026-10-06 09:29:38.227831-07', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0, 'choose a format', '2026-10-06 09:29:38.320897-07', NULL, NULL, NULL, true, '{"demo.setting": "kept"}');


--
-- Data for Name: memory_ref_images; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: memory_refs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.messages VALUES (345, 'j', 'swarm', '2026-10-06 09:29:38.28737-07', 'message from schema 18', NULL, NULL, 'coder');


--
-- Data for Name: name_pool; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.name_pool VALUES ('Homer Simpson', 'simpsons');
INSERT INTO public.name_pool VALUES ('Marge Simpson', 'simpsons');
INSERT INTO public.name_pool VALUES ('Bart Simpson', 'simpsons');
INSERT INTO public.name_pool VALUES ('Alice', 'english');
INSERT INTO public.name_pool VALUES ('Bob', 'english');


--
-- Data for Name: restarts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: transcript_image_refs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: transcript_images; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: transcripts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: blocker_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.blocker_events_id_seq', 2, true);


--
-- Name: blockers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.blockers_id_seq', 1, true);


--
-- Name: job_pauses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.job_pauses_id_seq', 1, false);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.messages_id_seq', 345, true);


--
-- Name: restarts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.restarts_id_seq', 1, false);


--
-- Name: agent_routes agent_routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_routes
    ADD CONSTRAINT agent_routes_pkey PRIMARY KEY (agent_key);


--
-- Name: agents agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (agent_key);


--
-- Name: blocker_events blocker_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocker_events
    ADD CONSTRAINT blocker_events_pkey PRIMARY KEY (id);


--
-- Name: blockers blockers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blockers
    ADD CONSTRAINT blockers_pkey PRIMARY KEY (id);


--
-- Name: board_meta board_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.board_meta
    ADD CONSTRAINT board_meta_pkey PRIMARY KEY (key);


--
-- Name: agents check_agents_name; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.agents
    ADD CONSTRAINT check_agents_name CHECK ((name ~ '^[A-Za-z0-9._''-](?:[A-Za-z0-9 ._''-]{0,62}[A-Za-z0-9._''-])?$'::text)) NOT VALID;


--
-- Name: memory_refs check_memory_refs_agent_name; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.memory_refs
    ADD CONSTRAINT check_memory_refs_agent_name CHECK ((agent_name ~ '^[A-Za-z0-9._''-](?:[A-Za-z0-9 ._''-]{0,62}[A-Za-z0-9._''-])?$'::text)) NOT VALID;


--
-- Name: messages check_messages_agent_name; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.messages
    ADD CONSTRAINT check_messages_agent_name CHECK ((agent_name ~ '^[A-Za-z0-9._''-](?:[A-Za-z0-9 ._''-]{0,62}[A-Za-z0-9._''-])?$'::text)) NOT VALID;


--
-- Name: messages check_messages_to_agent; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.messages
    ADD CONSTRAINT check_messages_to_agent CHECK (((to_agent IS NULL) OR (to_agent ~ '^[A-Za-z0-9._''-](?:[A-Za-z0-9 ._''-]{0,62}[A-Za-z0-9._''-])?$'::text))) NOT VALID;


--
-- Name: transcript_images check_transcript_images_sha256; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.transcript_images
    ADD CONSTRAINT check_transcript_images_sha256 CHECK ((sha256 ~ '^[0-9a-f]{64}$'::text)) NOT VALID;


--
-- Name: job_pauses job_pauses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_pauses
    ADD CONSTRAINT job_pauses_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (job);


--
-- Name: memory_ref_images memory_ref_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_ref_images
    ADD CONSTRAINT memory_ref_images_pkey PRIMARY KEY (document_id, sha256);


--
-- Name: memory_refs memory_refs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_refs
    ADD CONSTRAINT memory_refs_pkey PRIMARY KEY (document_id);


--
-- Name: messages messages_message_cap; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.messages
    ADD CONSTRAINT messages_message_cap CHECK ((length(message) <= 200)) NOT VALID;


--
-- Name: messages messages_message_nonempty; Type: CHECK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.messages
    ADD CONSTRAINT messages_message_nonempty CHECK ((length(message) > 0)) NOT VALID;


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: name_pool name_pool_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.name_pool
    ADD CONSTRAINT name_pool_pkey PRIMARY KEY (name);


--
-- Name: restarts restarts_old_agent_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restarts
    ADD CONSTRAINT restarts_old_agent_key_key UNIQUE (old_agent_key);


--
-- Name: restarts restarts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.restarts
    ADD CONSTRAINT restarts_pkey PRIMARY KEY (id);


--
-- Name: transcript_image_refs transcript_image_refs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcript_image_refs
    ADD CONSTRAINT transcript_image_refs_pkey PRIMARY KEY (job, agent_key, sha256);


--
-- Name: transcript_images transcript_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcript_images
    ADD CONSTRAINT transcript_images_pkey PRIMARY KEY (sha256);


--
-- Name: transcripts transcripts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcripts
    ADD CONSTRAINT transcripts_pkey PRIMARY KEY (job, agent_key);


--
-- Name: agents_active_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agents_active_name ON public.agents USING btree (name) WHERE (left_at IS NULL);


--
-- Name: agents_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX agents_job ON public.agents USING btree (job);


--
-- Name: agents_one_judge; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX agents_one_judge ON public.agents USING btree (job) WHERE (judge AND (left_at IS NULL));


--
-- Name: blocker_events_blocker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX blocker_events_blocker ON public.blocker_events USING btree (blocker, id);


--
-- Name: blockers_job_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX blockers_job_state ON public.blockers USING btree (job, state, id);


--
-- Name: job_pauses_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX job_pauses_job ON public.job_pauses USING btree (job, id);


--
-- Name: memory_ref_images_sha256; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX memory_ref_images_sha256 ON public.memory_ref_images USING btree (sha256);


--
-- Name: memory_refs_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX memory_refs_job ON public.memory_refs USING btree (job, agent_key);


--
-- Name: messages_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_created_at ON public.messages USING btree (created_at);


--
-- Name: messages_job_agent_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_job_agent_created_at ON public.messages USING btree (job, agent_name, created_at);


--
-- Name: messages_job_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_job_created_at ON public.messages USING btree (job, created_at);


--
-- Name: messages_job_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_job_id ON public.messages USING btree (job, id);


--
-- Name: messages_to_agent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_to_agent ON public.messages USING btree (to_agent, id) WHERE (to_agent IS NOT NULL);


--
-- Name: restarts_host_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX restarts_host_at ON public.restarts USING btree (host, os_user, at);


--
-- Name: restarts_job; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX restarts_job ON public.restarts USING btree (job, agent_key);


--
-- Name: transcript_image_refs_sha256; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transcript_image_refs_sha256 ON public.transcript_image_refs USING btree (sha256);


--
-- Name: transcripts_agent_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transcripts_agent_name ON public.transcripts USING btree (agent_name);


--
-- Name: transcripts_captured_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX transcripts_captured_at ON public.transcripts USING btree (captured_at);


--
-- Name: agents agents_state_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER agents_state_notify AFTER INSERT OR DELETE OR UPDATE ON public.agents FOR EACH STATEMENT EXECUTE FUNCTION public.swarm_state_notify();


--
-- Name: jobs jobs_keep_blocked_jobs; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER jobs_keep_blocked_jobs BEFORE UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.swarm_keep_blocked_jobs();


--
-- Name: jobs jobs_keep_goal_jobs; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER jobs_keep_goal_jobs BEFORE UPDATE ON public.jobs FOR EACH ROW EXECUTE FUNCTION public.swarm_keep_goal_jobs();


--
-- Name: jobs jobs_state_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER jobs_state_notify AFTER INSERT OR DELETE OR UPDATE ON public.jobs FOR EACH STATEMENT EXECUTE FUNCTION public.swarm_state_notify();


--
-- Name: messages messages_notify; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER messages_notify AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.swarm_notify();


--
-- Name: agents agents_job_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_job_fkey FOREIGN KEY (job) REFERENCES public.jobs(job) ON DELETE CASCADE;


--
-- Name: blocker_events blocker_events_blocker_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.blocker_events
    ADD CONSTRAINT blocker_events_blocker_fkey FOREIGN KEY (blocker) REFERENCES public.blockers(id);


--
-- Name: memory_ref_images memory_ref_images_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_ref_images
    ADD CONSTRAINT memory_ref_images_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.memory_refs(document_id) ON DELETE CASCADE;


--
-- Name: memory_ref_images memory_ref_images_sha256_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memory_ref_images
    ADD CONSTRAINT memory_ref_images_sha256_fkey FOREIGN KEY (sha256) REFERENCES public.transcript_images(sha256);


--
-- Name: messages messages_job_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_job_fkey FOREIGN KEY (job) REFERENCES public.jobs(job) ON DELETE CASCADE;


--
-- Name: transcript_image_refs transcript_image_refs_sha256_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcript_image_refs
    ADD CONSTRAINT transcript_image_refs_sha256_fkey FOREIGN KEY (sha256) REFERENCES public.transcript_images(sha256);


--
-- PostgreSQL database dump complete
--
