-- Generated by main 8d8f66a schema 17 setup; no blockers tables.
BEGIN TRANSACTION;
CREATE TABLE agent_routes (
    agent_key  TEXT PRIMARY KEY,
    session_id TEXT,
    state      TEXT NOT NULL CHECK (state IN ('pending', 'unverified', 'final')),
    job        TEXT,
    created_at TEXT NOT NULL
);
CREATE TABLE agents (
    agent_key          TEXT PRIMARY KEY,
    name               TEXT NOT NULL CHECK (length(name) > 0),
    job                TEXT NOT NULL REFERENCES jobs(job) ON DELETE CASCADE,
    role               TEXT,
    host               TEXT,
    joined_at          TEXT NOT NULL,
    last_seen          TEXT NOT NULL,
    last_read_id       INTEGER NOT NULL DEFAULT 0,
    left_at            TEXT,
    state              TEXT NOT NULL DEFAULT 'started'
                       CHECK (state IN ('started', 'running', 'completed', 'left', 'dead')),
    tool_calls         INTEGER NOT NULL DEFAULT 0,
    current_tool       TEXT,
    tool_started_at    TEXT,
    last_post_at       TEXT,
    roster_seen        TEXT,
    roster_synced_at   TEXT,
    memory_recalled_at TEXT,
    memory_seen        TEXT NOT NULL DEFAULT '[]',
    remembered_at      TEXT,
    nudged_at          TEXT,
    reply_reminded_id  INTEGER NOT NULL DEFAULT 0,
    calls_at_post      INTEGER NOT NULL DEFAULT 0,
    silence_nudged_at  TEXT,
    judge              INTEGER NOT NULL DEFAULT 0,
    spawns             INTEGER NOT NULL DEFAULT 0,
    verifier           INTEGER NOT NULL DEFAULT 0
, harness TEXT, model TEXT, turn_ended_at TEXT, os_user TEXT, left_reason TEXT, resume_of TEXT);
CREATE TABLE board_changes (kind TEXT PRIMARY KEY, n INTEGER NOT NULL DEFAULT 0);
INSERT INTO "board_changes" VALUES('messages',1);
INSERT INTO "board_changes" VALUES('state',3);
CREATE TABLE board_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT INTO "board_meta" VALUES('message_max_chars','200');
CREATE TABLE job_pauses (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    job          TEXT NOT NULL,
    paused_at    TEXT NOT NULL,
    paused_by    TEXT,
    reason       TEXT,
    manifest     TEXT NOT NULL,
    resumed_at   TEXT,
    resumed_by   TEXT,
    resumed_host TEXT,
    outcome      TEXT
);
CREATE TABLE jobs (
    job               TEXT PRIMARY KEY,
    description       TEXT,
    created_by        TEXT,
    created_at        TEXT NOT NULL,
    task              TEXT,
    status            TEXT NOT NULL DEFAULT 'active'
                      CHECK (status IN ('active', 'paused', 'completed', 'cancelled', 'failed')),
    outcome           TEXT,
    session_id        TEXT,
    activated_at      TEXT,
    finished_at       TEXT,
    project           TEXT,
    goal              TEXT,
    verdict           TEXT CHECK (verdict IN ('met', 'not_met')),
    verdict_reason    TEXT,
    verdict_next      TEXT,
    verdict_by        TEXT,
    verdict_at        TEXT,
    completion_forced INTEGER NOT NULL DEFAULT 0,
    spawns            INTEGER NOT NULL DEFAULT 0,
    waiting_on        TEXT,
    waiting_since     TEXT,
    waiting_until     TEXT,
    max_hours         REAL,
    plugin_data       TEXT
, closed_by TEXT, supervise INTEGER NOT NULL DEFAULT 1);
INSERT INTO "jobs" VALUES('j','main board','human','2026-10-06T15:15:36.546120+00:00',NULL,'active',NULL,NULL,'2026-10-06T15:15:36.546120+00:00',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,'{"demo.setting": "kept"}',NULL,1);
CREATE TABLE memory_ref_images (
    document_id TEXT NOT NULL,
    sha256      TEXT NOT NULL REFERENCES transcript_images (sha256),
    PRIMARY KEY (document_id, sha256)
);
CREATE TABLE memory_refs (
    document_id  TEXT PRIMARY KEY,
    bank         TEXT NOT NULL,
    job          TEXT NOT NULL,
    agent_key    TEXT NOT NULL,
    agent_name   TEXT NOT NULL,
    harness      TEXT,
    host         TEXT,
    session_id   TEXT,
    tool_call_id TEXT,
    -- The writer is a name from [provenance] writers, or swarm-remember (checked by save_memory_ref).
    writer       TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    checked_at   TEXT,
    patched      INTEGER NOT NULL DEFAULT 0,
    raw_bytes    INTEGER NOT NULL DEFAULT 0,
    redactions   INTEGER NOT NULL DEFAULT 0,
    excerpt      BLOB
);
CREATE TABLE messages (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    job        TEXT NOT NULL REFERENCES jobs(job) ON DELETE CASCADE,
    agent_name TEXT NOT NULL CHECK (length(agent_name) > 0),
    created_at TEXT NOT NULL,
    message    TEXT NOT NULL CHECK (length(message) >= 1),
    to_agent   TEXT,
    agent_key  TEXT,
    host       TEXT
);
INSERT INTO "messages" VALUES(1,'j','swarm','2026-10-06T15:15:36.546303+00:00','message from schema 17',NULL,NULL,'coder');
CREATE TABLE name_pool (
    name   TEXT PRIMARY KEY,
    source TEXT NOT NULL CHECK (source IN ('simpsons', 'english'))
);
INSERT INTO "name_pool" VALUES('Homer Simpson','simpsons');
INSERT INTO "name_pool" VALUES('Marge Simpson','simpsons');
INSERT INTO "name_pool" VALUES('Bart Simpson','simpsons');
INSERT INTO "name_pool" VALUES('Alice','english');
INSERT INTO "name_pool" VALUES('Bob','english');
CREATE TABLE restarts (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    job           TEXT NOT NULL,
    agent_key     TEXT NOT NULL,          -- the lineage root: the first agent of the chain
    attempt       INTEGER NOT NULL,
    at            TEXT NOT NULL,
    reason        TEXT NOT NULL,
    old_agent_key TEXT NOT NULL UNIQUE,
    new_agent_key TEXT,
    harness       TEXT NOT NULL,
    host          TEXT NOT NULL,
    os_user       TEXT NOT NULL,
    minutes_cap   REAL NOT NULL,
    ended_at      TEXT,
    outcome       TEXT
);
CREATE TABLE transcript_image_refs (
    job       TEXT NOT NULL,
    agent_key TEXT NOT NULL,
    sha256    TEXT NOT NULL REFERENCES transcript_images (sha256),
    PRIMARY KEY (job, agent_key, sha256)
);
CREATE TABLE transcript_images (
    sha256     TEXT PRIMARY KEY,
    mime       TEXT NOT NULL,
    bytes      INTEGER NOT NULL,
    data       BLOB NOT NULL,
    first_seen TEXT NOT NULL
);
CREATE TABLE transcripts (
    job          TEXT NOT NULL,
    agent_key    TEXT NOT NULL,
    agent_name   TEXT NOT NULL,
    role         TEXT NOT NULL CHECK (role IN ('subagent', 'orchestrator')),
    host         TEXT,
    session_id   TEXT,
    captured_at  TEXT NOT NULL,
    final        INTEGER NOT NULL DEFAULT 0,
    raw_bytes    INTEGER NOT NULL,
    stored_bytes INTEGER NOT NULL,
    redactions   INTEGER NOT NULL DEFAULT 0,
    sha256       TEXT NOT NULL,
    body         BLOB NOT NULL, harness TEXT, capture_failed TEXT,
    PRIMARY KEY (job, agent_key)
);
CREATE UNIQUE INDEX agents_active_name ON agents (name) WHERE left_at IS NULL;
CREATE UNIQUE INDEX agents_one_judge ON agents (job) WHERE judge AND left_at IS NULL;
CREATE INDEX agents_job ON agents (job);
CREATE INDEX messages_job_id ON messages (job, id);
CREATE INDEX messages_created_at ON messages (created_at);
CREATE INDEX messages_job_created_at ON messages (job, created_at);
CREATE INDEX messages_to_agent ON messages (to_agent, id) WHERE to_agent IS NOT NULL;
CREATE INDEX transcripts_captured_at ON transcripts (captured_at);
CREATE INDEX transcripts_agent_name ON transcripts (agent_name);
CREATE INDEX transcript_image_refs_sha256 ON transcript_image_refs (sha256);
CREATE INDEX memory_refs_job ON memory_refs (job, agent_key);
CREATE INDEX memory_ref_images_sha256 ON memory_ref_images (sha256);
CREATE INDEX restarts_job ON restarts (job, agent_key);
CREATE INDEX restarts_host_at ON restarts (host, os_user, at);
CREATE INDEX job_pauses_job ON job_pauses (job, id);
CREATE TRIGGER check_messages_cap BEFORE INSERT ON messages
    WHEN length(NEW.message) > (SELECT CAST(value AS INTEGER) FROM board_meta WHERE key = 'message_max_chars')
    BEGIN SELECT RAISE(ABORT, 'message too long'); END;
CREATE TRIGGER messages_changed AFTER INSERT ON messages BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind IN ('messages', 'state'); END;
CREATE TRIGGER agents_inserted AFTER INSERT ON agents BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER agents_updated AFTER UPDATE ON agents BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER agents_deleted AFTER DELETE ON agents BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER jobs_inserted AFTER INSERT ON jobs BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER jobs_updated AFTER UPDATE ON jobs BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER jobs_deleted AFTER DELETE ON jobs BEGIN
    UPDATE board_changes SET n = n + 1 WHERE kind = 'state'; END;
CREATE TRIGGER check_messages_names_ins BEFORE INSERT ON messages WHEN NOT ((typeof(NEW.agent_name) = 'text' AND length(NEW.agent_name) BETWEEN 1 AND 64 AND NEW.agent_name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.agent_name NOT GLOB ' *' AND NEW.agent_name NOT GLOB '* ') AND (NEW.to_agent IS NULL OR (typeof(NEW.to_agent) = 'text' AND length(NEW.to_agent) BETWEEN 1 AND 64 AND NEW.to_agent NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.to_agent NOT GLOB ' *' AND NEW.to_agent NOT GLOB '* '))) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_messages_names_upd BEFORE UPDATE OF agent_name, to_agent ON messages WHEN NOT ((typeof(NEW.agent_name) = 'text' AND length(NEW.agent_name) BETWEEN 1 AND 64 AND NEW.agent_name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.agent_name NOT GLOB ' *' AND NEW.agent_name NOT GLOB '* ') AND (NEW.to_agent IS NULL OR (typeof(NEW.to_agent) = 'text' AND length(NEW.to_agent) BETWEEN 1 AND 64 AND NEW.to_agent NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.to_agent NOT GLOB ' *' AND NEW.to_agent NOT GLOB '* '))) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_agents_name_ins BEFORE INSERT ON agents WHEN NOT ((typeof(NEW.name) = 'text' AND length(NEW.name) BETWEEN 1 AND 64 AND NEW.name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.name NOT GLOB ' *' AND NEW.name NOT GLOB '* ')) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_agents_name_upd BEFORE UPDATE OF name ON agents WHEN NOT ((typeof(NEW.name) = 'text' AND length(NEW.name) BETWEEN 1 AND 64 AND NEW.name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.name NOT GLOB ' *' AND NEW.name NOT GLOB '* ')) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_transcript_images_sha256_ins BEFORE INSERT ON transcript_images WHEN NOT ((typeof(NEW.sha256) = 'text' AND length(NEW.sha256) = 64 AND NEW.sha256 NOT GLOB '*[^0-9a-f]*')) BEGIN SELECT RAISE(ABORT, 'invalid image sha256'); END;
CREATE TRIGGER check_transcript_images_sha256_upd BEFORE UPDATE OF sha256 ON transcript_images WHEN NOT ((typeof(NEW.sha256) = 'text' AND length(NEW.sha256) = 64 AND NEW.sha256 NOT GLOB '*[^0-9a-f]*')) BEGIN SELECT RAISE(ABORT, 'invalid image sha256'); END;
CREATE TRIGGER check_memory_refs_name_ins BEFORE INSERT ON memory_refs WHEN NOT ((typeof(NEW.agent_name) = 'text' AND length(NEW.agent_name) BETWEEN 1 AND 64 AND NEW.agent_name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.agent_name NOT GLOB ' *' AND NEW.agent_name NOT GLOB '* ')) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_memory_refs_name_upd BEFORE UPDATE OF agent_name ON memory_refs WHEN NOT ((typeof(NEW.agent_name) = 'text' AND length(NEW.agent_name) BETWEEN 1 AND 64 AND NEW.agent_name NOT GLOB '*[^A-Za-z0-9 ._''-]*' AND NEW.agent_name NOT GLOB ' *' AND NEW.agent_name NOT GLOB '* ')) BEGIN SELECT RAISE(ABORT, 'invalid agent name'); END;
CREATE TRIGGER check_memory_ref_images_sha256_ins BEFORE INSERT ON memory_ref_images WHEN NOT ((typeof(NEW.sha256) = 'text' AND length(NEW.sha256) = 64 AND NEW.sha256 NOT GLOB '*[^0-9a-f]*')) BEGIN SELECT RAISE(ABORT, 'invalid image sha256'); END;
CREATE TRIGGER check_memory_ref_images_sha256_upd BEFORE UPDATE OF sha256 ON memory_ref_images WHEN NOT ((typeof(NEW.sha256) = 'text' AND length(NEW.sha256) = 64 AND NEW.sha256 NOT GLOB '*[^0-9a-f]*')) BEGIN SELECT RAISE(ABORT, 'invalid image sha256'); END;
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('messages',1);
COMMIT;
PRAGMA user_version=17;
